#!/bin/bash
set -x
set -e
git clone https://github.com/jojimt/$1
cd $1
git remote add upstream https://github.com/contiv/$1
git fetch upstream
git checkout master
git merge upstream/master
git push
git status

